import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import styles from '../styles/Home.module.css'

function submitEmail(e: React.SyntheticEvent) {
  e.preventDefault()
  const target = e.target as typeof e.target & {
    email: { value: string };
    password: { value: string };
  };
  target.email.value;
}

const Home: NextPage = () => {
  return (
    <div className="mx-4 sm:mx-16 lg:mx-32">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex my-3">
          <Link href={"/"}>
            <a className="font-bold">Async Chess Coach</a>
          </Link>

          {/* <div className=" ml-auto mr-6">
            <Link href={"/about"}>
              <a className="mr-3">About</a>
            </Link> */}

            {/* <Link href={"/signup"}>
              <a>Sign Up</a>
            </Link> */}
          {/* </div> */}
      </div>

      <main className="justify-center align-center mt-14 md:mt-24">

        <div className="mx-auto md:flex justify-center">
          <div className="text-left self-center mb-4 md:mr-8">

            <h1 className="font-semibold text-3xl my-2">
              Get your chess games analyzed by experts
            </h1>

            <h5 className="text-md">
              AsyncCoach automatically pulls your games to keep your feedback fresh.
            </h5>

            <form className=" bg-opacity-50 bg-black inline-flex mt-2" onSubmit={submitEmail}>
              <input className="flex-4 border border-gray-500 pl-1" placeholder="email address"></input>
              <button className="flex-1 text-white bg-red-600 p-2">Sign Up</button>
            </form>
          </div>

          <div className="hidden md:flex justify-between">
            <Image className="rounded-xl mx-3" alt="chess piece" width={300} height={250} src="https://images.unsplash.com/photo-1538221566857-f20f826391c6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1771&q=80"/>
            {/* <Image className="!hidden rounded-xl" alt="chess piece" width={300} height={250} src="https://images.unsplash.com/photo-1538221566857-f20f826391c6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1771&q=80"/> */}
          </div>
        </div>
        
        <div className="items-center text-center ">
          <div>Integrated with:</div>
          <div className="font-semibold">
            lichess &#8226; chess.com
          </div>
        </div>

        <div className="flex align-center justify-center flex-wrap mt-3">
          <div className={styles.card}>
            <div className="flex items-center">
              <h2 className="!mr-4">Hands Free</h2>
              <div className="block">
                <Image alt="clock" height={30} width={30} src={"/sync.png"}/>
              </div>
            </div>
            <p>Your games automatically sync with Async Coach, no need to upload anything</p>
          </div>

          <div className={styles.card}>
          <div className="flex items-center">
            <h2 className="!mr-4">Personalized</h2>
              <div className="block">
                <Image alt="personalized" height={40} width={40} src={"/exchange.png"}/>
              </div>
            </div>
            <p>Coaches can track your progress over time to focus on identifying problem areas</p>
          </div>

          <div className={styles.card}>
            <div className="flex items-center">
              <h2 className="!mr-4">Save Time</h2>
              <div className="block">
                <Image alt="clock" height={40} width={40} src={"/clock.png"}/>
              </div>
            </div>
            <p>Let experts look at your play and pin point exactly what you need to play better chess</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <div className="block">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <div className="block">
          <a href="https://www.flaticon.com/free-icons/quick" title="quick icons">Quick icons created by kornkun - Flaticon</a>
          <a href="https://www.flaticon.com/free-icons/personalization" title="personalization icons">Personalization icons created by Freepik - Flaticon</a>
          <a href="https://www.flaticon.com/free-icons/sync" title="sync icons">Sync icons created by Freepik - Flaticon</a>
        </div>
        </div>
      </footer>
    </div>
  )
}

export default Home
